[mypy]
python_version = 3.12
incremental = False
namespace_packages = True
explicit_package_bases = True
strict_optional = False

[mypy-sklearn.*,transformers.*,flask_frozen.*,flaskext.*,ics.*]
ignore_missing_imports = True

[mypy-pandas.*,bs4.*,pdfrw.*,titlecase.*,torch.*,gdown.*,icalendar.*,markdown_it.*,tzlocal.*,scripts.*]
ignore_missing_imports = True
